collections:
  m:
    output: true
    permalink: /m/:path/
  m_redirects:
    output: true
    permalink: /m/:path/

defaults:
  - scope:
      path: ""
      type: m
    output: true
    values:
      layout: maerke

paymentsSiteUrl: "http://localhost:3000"
defaultShippingPrice: 35
