collections:
  m:
    output: true
    permalink: /m/:path/index.html

defaults:
  - scope:
      path: ""
      type: m
    output: true
    values:
      layout: maerke

baseurl: /spejdermaerker.dk
